/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_NTCIPVehicleClass_H_
#define	_NTCIPVehicleClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NTCIPVehicleClass */
typedef OCTET_STRING_t	 NTCIPVehicleClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NTCIPVehicleClass;
asn_struct_free_f NTCIPVehicleClass_free;
asn_struct_print_f NTCIPVehicleClass_print;
asn_constr_check_f NTCIPVehicleClass_constraint;
ber_type_decoder_f NTCIPVehicleClass_decode_ber;
der_type_encoder_f NTCIPVehicleClass_encode_der;
xer_type_decoder_f NTCIPVehicleClass_decode_xer;
xer_type_encoder_f NTCIPVehicleClass_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NTCIPVehicleClass_H_ */
