/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RequestEntry_H_
#define	_RequestEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RequestEntry */
typedef long	 RequestEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestEntry;
asn_struct_free_f RequestEntry_free;
asn_struct_print_f RequestEntry_print;
asn_constr_check_f RequestEntry_constraint;
ber_type_decoder_f RequestEntry_decode_ber;
der_type_encoder_f RequestEntry_encode_der;
xer_type_decoder_f RequestEntry_decode_xer;
xer_type_encoder_f RequestEntry_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestEntry_H_ */
