/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_VehicleID_H_
#define	_VehicleID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleID */
typedef OCTET_STRING_t	 VehicleID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleID;
asn_struct_free_f VehicleID_free;
asn_struct_print_f VehicleID_print;
asn_constr_check_f VehicleID_constraint;
ber_type_decoder_f VehicleID_decode_ber;
der_type_encoder_f VehicleID_encode_der;
xer_type_decoder_f VehicleID_decode_xer;
xer_type_encoder_f VehicleID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleID_H_ */
