/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_BSMtype_H_
#define	_BSMtype_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum msgID {
	msgID_reserved	= 0,
	msgID_alaCarteMessage	= 1,
	msgID_basicSafetyMessage	= 2,
	msgID_basicSafetyMessageVerbose	= 3,
	msgID_commonSafetyRequest	= 4,
	msgID_emergencyVehicleAlert	= 5,
	msgID_intersectionCollisionAlert	= 6,
	msgID_mapData	= 7,
	msgID_nmeaCorrections	= 8,
	msgID_probeDataManagement	= 9,
	msgID_probeVehicleData	= 10,
	msgID_roadSideAlert	= 11,
	msgID_rtcmCorrections	= 12,
	msgID_signalPhaseAndTimingMessage	= 13,
	msgID_signalRequestMessage	= 14,
	msgID_signalStatusMessage	= 15,
	msgID_travelerInformation	= 16
} e_msgID;

/* BSMtype */
typedef struct BSMtype {
	long	 msgID;
	OCTET_STRING_t	 bsmBlob;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BSMtype_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msgID_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BSMtype;

#ifdef __cplusplus
}
#endif

#endif	/* _BSMtype_H_ */
