/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_DMonth_H_
#define	_DMonth_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DMonth */
typedef long	 DMonth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DMonth;
asn_struct_free_f DMonth_free;
asn_struct_print_f DMonth_print;
asn_constr_check_f DMonth_constraint;
ber_type_decoder_f DMonth_decode_ber;
der_type_encoder_f DMonth_encode_der;
xer_type_decoder_f DMonth_decode_xer;
xer_type_encoder_f DMonth_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DMonth_H_ */
