#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=45

start() {
	. /lib/firewall/uci_firewall.sh ip6tables firewall.ipv6
	fw_init
	. /lib/firewall/uci_firewall.sh iptables firewall.ipv4
	fw_init
	fw_init_if
}

stop() {
	. /lib/firewall/uci_firewall.sh ip6tables firewall.ipv6
	fw_stop	
	. /lib/firewall/uci_firewall.sh iptables firewall.ipv4
	fw_stop	
}
