#!/bin/sh /etc/rc.common
## This is a script to load all the MMITSS applications
## Author : Sriharsha Mucheli
## University of Arizona

START=95

start() {
	/etc/init.d/wmefwd stop
	sleep 1
	/etc/init.d/wmefwd start
	sleep 1
	/etc/init.d/firewall stop
	sleep 1
	/usr/local/bin/MMITSS_MRP_MAP_SPAT_Broadcast 127.0.0.1 127.0.0.1 0 > /nojournal/bin/log/MMITSS_MRP_MAP_SPAT_BROADCAST.log 2>&1 &
	sleep 1
	/usr/local/bin/MMITSS_MRP_PriorityRequestServer_road_final > /nojournal/bin/log/MMITSS_MRP_PriorityRequestServer_road_final.log 2>&1 &
	sleep 1
	/usr/local/bin/MMITSS_MRP_Priority_Solver > /nojournal/bin/log/MMITSS_MRP_Priority_Solver.log  2>&1 &
	sleep 1
	/usr/local/bin/MMITSS_MRP_TrafficControllerInterface_forceoffTest > /nojournal/bin/log/MMITSS_MRP_TrafficControllerInterface_forceofftest.log 2>&1 &
	sleep 1
	/usr/local/bin/MMITSS_rsu_BSM_Receiver 3333 3.6 0 > /nojournal/bin/log/MMITSS_rsu_BSM_Receiver.log 2>&1 &
	sleep 1
	/usr/local/bin/MMITSS_MRP_PerformanceObserver_Field 3333 0.5 10.254.56.199 > /nojournal/bin/log/MMITSS_MRP_PerformanceObserver.log 2>&1 &

}

stop() {
	pkill -9 MMITSS
	sleep 1
	/etc/init.d/wmefwd stop
}

