/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_IntersectionState_H_
#define	_IntersectionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "IntersectionID.h"
#include "IntersectionStatusObject.h"
#include "TimeMark.h"
#include <NativeInteger.h>
#include "SignalState.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MovementState;

/* IntersectionState */
typedef struct IntersectionState {
	DescriptiveName_t	*name	/* OPTIONAL */;
	IntersectionID_t	 id;
	IntersectionStatusObject_t	 status;
	TimeMark_t	*timeStamp	/* OPTIONAL */;
	long	*lanesCnt	/* OPTIONAL */;
	struct states {
		A_SEQUENCE_OF(struct MovementState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} states;
	SignalState_t	*priority	/* OPTIONAL */;
	SignalState_t	*preempt	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionState;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MovementState.h"

#endif	/* _IntersectionState_H_ */
