/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_IntersectionID_H_
#define	_IntersectionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionID */
typedef OCTET_STRING_t	 IntersectionID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionID;
asn_struct_free_f IntersectionID_free;
asn_struct_print_f IntersectionID_print;
asn_constr_check_f IntersectionID_constraint;
ber_type_decoder_f IntersectionID_decode_ber;
der_type_encoder_f IntersectionID_encode_der;
xer_type_decoder_f IntersectionID_decode_xer;
xer_type_encoder_f IntersectionID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionID_H_ */
