/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_LaneCount_H_
#define	_LaneCount_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LaneCount */
typedef long	 LaneCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneCount;
asn_struct_free_f LaneCount_free;
asn_struct_print_f LaneCount_print;
asn_constr_check_f LaneCount_constraint;
ber_type_decoder_f LaneCount_decode_ber;
der_type_encoder_f LaneCount_encode_der;
xer_type_decoder_f LaneCount_decode_xer;
xer_type_encoder_f LaneCount_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneCount_H_ */
