/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PedestrianDetect_H_
#define	_PedestrianDetect_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PedestrianDetect {
	PedestrianDetect_none	= 0,
	PedestrianDetect_maybe	= 1,
	PedestrianDetect_one	= 2,
	PedestrianDetect_some	= 3
} e_PedestrianDetect;

/* PedestrianDetect */
typedef long	 PedestrianDetect_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PedestrianDetect;
asn_struct_free_f PedestrianDetect_free;
asn_struct_print_f PedestrianDetect_print;
asn_constr_check_f PedestrianDetect_constraint;
ber_type_decoder_f PedestrianDetect_decode_ber;
der_type_encoder_f PedestrianDetect_encode_der;
xer_type_decoder_f PedestrianDetect_decode_xer;
xer_type_encoder_f PedestrianDetect_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PedestrianDetect_H_ */
