/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignalLightState_H_
#define	_SignalLightState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalLightState */
typedef long	 SignalLightState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalLightState;
asn_struct_free_f SignalLightState_free;
asn_struct_print_f SignalLightState_print;
asn_constr_check_f SignalLightState_constraint;
ber_type_decoder_f SignalLightState_decode_ber;
der_type_encoder_f SignalLightState_encode_der;
xer_type_decoder_f SignalLightState_decode_xer;
xer_type_encoder_f SignalLightState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalLightState_H_ */
