/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735SPATMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignalState_H_
#define	_SignalState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalState */
typedef OCTET_STRING_t	 SignalState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalState;
asn_struct_free_f SignalState_free;
asn_struct_print_f SignalState_print;
asn_constr_check_f SignalState_constraint;
ber_type_decoder_f SignalState_decode_ber;
der_type_encoder_f SignalState_encode_der;
xer_type_decoder_f SignalState_decode_xer;
xer_type_encoder_f SignalState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalState_H_ */
