#!/bin/bash

# Define colors:
red='\033[0;31m'
green='\033[0;32m'
nocolor='\033[0m'

read -p "Enter absolute path to the raw BSM data: " -e inputFile
read -p "Enter absolute path to the configuration file: " -e configFile
outputFile=$(echo "$inputFile" | sed "s/.csv/_processed.csv/")

if [[ "$inputFile" == *".csv"* ]]; then
    cd src
    echo "Building MapBsmProcessor..."
    make clean &> /dev/null
    make linux &> /dev/null
    # Indicate Success/Failure of the build
    if [ "$?" -eq "0" ]; then
        echo -e "${green}Successful${nocolor}"
    else
	    echo -e "${red}Failed${nocolor}"
        exit
    fi
    sleep 1s
    
    echo "Processing the data from map-engine..."
    ./MapBsmProcessor $inputFile $configFile > /dev/null 2>&1
    sleep 1s

    echo "Processing local coordinates and dependent variables..."
    python3 LocalCoordinateProcessor.py $outputFile $configFile >/dev/null 2>&1
    sleep 1s

    echo "Data processing is now complete. Removing autogenerated files..."
    rm -r __pycache__
    make clean &> /dev/null
    rm ../config/*.payload

    sleep 1s
    echo "If successful, processed data will be available at ${outputFile}."
    sleep 1s

else
    echo "Invalid Filename. Filename must be of (*.csv) format."
    sleep 1s
fi
