/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_NTCIPVehicleclass_H_
#define	_NTCIPVehicleclass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NTCIPVehicleclass */
typedef OCTET_STRING_t	 NTCIPVehicleclass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NTCIPVehicleclass;
asn_struct_free_f NTCIPVehicleclass_free;
asn_struct_print_f NTCIPVehicleclass_print;
asn_constr_check_f NTCIPVehicleclass_constraint;
ber_type_decoder_f NTCIPVehicleclass_decode_ber;
der_type_encoder_f NTCIPVehicleclass_encode_der;
xer_type_decoder_f NTCIPVehicleclass_decode_xer;
xer_type_encoder_f NTCIPVehicleclass_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NTCIPVehicleclass_H_ */
