/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_VINstring_H_
#define	_VINstring_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VINstring */
typedef OCTET_STRING_t	 VINstring_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VINstring;
asn_struct_free_f VINstring_free;
asn_struct_print_f VINstring_print;
asn_constr_check_f VINstring_constraint;
ber_type_decoder_f VINstring_decode_ber;
der_type_encoder_f VINstring_encode_der;
xer_type_decoder_f VINstring_decode_xer;
xer_type_encoder_f VINstring_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VINstring_H_ */
