/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735MAPMESSAGE"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_MAP_H_
#define	_MAP_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "MsgCount.h"
#include "DescriptiveName.h"
#include "LayerType.h"
#include "LayerID.h"
#include "MsgCRC.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DataParameters;
struct Intersection;

/* MAP */
typedef struct MAP {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	DescriptiveName_t	*name	/* OPTIONAL */;
	LayerType_t	*layerType	/* OPTIONAL */;
	LayerID_t	*layerID	/* OPTIONAL */;
	struct intersections {
		A_SEQUENCE_OF(struct Intersection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} intersections;
	struct DataParameters	*dataParameters	/* OPTIONAL */;
	MsgCRC_t	 crc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAP;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataParameters.h"
#include "Intersection.h"

#endif	/* _MAP_H_ */
