/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "PSM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ActivePriority_H_
#define	_ActivePriority_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ActivePriority */
typedef BOOLEAN_t	 ActivePriority_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActivePriority;
asn_struct_free_f ActivePriority_free;
asn_struct_print_f ActivePriority_print;
asn_constr_check_f ActivePriority_constraint;
ber_type_decoder_f ActivePriority_decode_ber;
der_type_encoder_f ActivePriority_encode_der;
xer_type_decoder_f ActivePriority_decode_xer;
xer_type_encoder_f ActivePriority_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ActivePriority_H_ */
