/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "SRM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DHour_H_
#define	_DHour_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DHour */
typedef long	 DHour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DHour;
asn_struct_free_f DHour_free;
asn_struct_print_f DHour_print;
asn_constr_check_f DHour_constraint;
ber_type_decoder_f DHour_decode_ber;
der_type_encoder_f DHour_encode_der;
xer_type_decoder_f DHour_decode_xer;
xer_type_encoder_f DHour_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DHour_H_ */
