/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "SRM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DMinute_H_
#define	_DMinute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DMinute */
typedef long	 DMinute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DMinute;
asn_struct_free_f DMinute_free;
asn_struct_print_f DMinute_print;
asn_constr_check_f DMinute_constraint;
ber_type_decoder_f DMinute_decode_ber;
der_type_encoder_f DMinute_encode_der;
xer_type_decoder_f DMinute_decode_xer;
xer_type_encoder_f DMinute_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DMinute_H_ */
