/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "PSM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_NumberOfRequests_H_
#define	_NumberOfRequests_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberOfRequests */
typedef long	 NumberOfRequests_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfRequests;
asn_struct_free_f NumberOfRequests_free;
asn_struct_print_f NumberOfRequests_print;
asn_constr_check_f NumberOfRequests_constraint;
ber_type_decoder_f NumberOfRequests_decode_ber;
der_type_encoder_f NumberOfRequests_encode_der;
xer_type_decoder_f NumberOfRequests_decode_xer;
xer_type_encoder_f NumberOfRequests_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfRequests_H_ */
