/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "PSM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_PSM_H_
#define	_PSM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "IntersectionID.h"
#include "NumberOfRequests.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ActiveRequestTable;

/* PSM */
typedef struct PSM {
	DSRCmsgID_t	 msgID;
	IntersectionID_t	 id;
	NumberOfRequests_t	 numberOfRequests;
	struct activeRequestTable {
		A_SEQUENCE_OF(struct ActiveRequestTable) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} activeRequestTable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PSM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PSM;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ActiveRequestTable.h"

#endif	/* _PSM_H_ */
