/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "PSM.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_VehicleState_H_
#define	_VehicleState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleState {
	VehicleState_approaching	= 1,
	VehicleState_leaving	= 2,
	VehicleState_inQueue	= 3,
	VehicleState_inIntersection	= 4,
	VehicleState_outOfMap	= 5,
	VehicleState_dwelling	= 6,
	VehicleState_isCanceled	= 7
} e_VehicleState;

/* VehicleState */
typedef long	 VehicleState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleState;
asn_struct_free_f VehicleState_free;
asn_struct_print_f VehicleState_print;
asn_constr_check_f VehicleState_constraint;
ber_type_decoder_f VehicleState_decode_ber;
der_type_encoder_f VehicleState_encode_der;
xer_type_decoder_f VehicleState_decode_xer;
xer_type_encoder_f VehicleState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleState_H_ */
