/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "J2735MAPMESSAGE"
 * 	found in "MAP.txt"
 * 	`asn1c -fnative-types`
 */

#ifndef	_VehicleComputedLane_H_
#define	_VehicleComputedLane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneNumber.h"
#include "LaneWidth.h"
#include "VehicleLaneAttributes.h"
#include "DrivenLineOffset.h"
#include "ConnectsTo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeList;

/* VehicleComputedLane */
typedef struct VehicleComputedLane {
	LaneNumber_t	 laneNumber;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	VehicleLaneAttributes_t	*laneAttributes	/* OPTIONAL */;
	LaneNumber_t	 refLaneNum;
	DrivenLineOffset_t	 lineOffset;
	struct NodeList	*keepOutList	/* OPTIONAL */;
	ConnectsTo_t	*connectsTo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleComputedLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleComputedLane;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeList.h"

#endif	/* _VehicleComputedLane_H_ */
